name: Update Docs

on: push

jobs:
  copy_to_complete:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: /README.md
          dst_path: /README.md
          dst_owner: MRU-CSIS-1501-DEV-PLAYGROUND
          dst_repo_name: syntax-error-safari-completed
          username: jpratt-mru
          email: jpratt@mtroyal.ca

  copy_to_template:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: /README.md
          dst_path: /README.md
          dst_owner: MRU-CSIS-1501-DEV-PLAYGROUND
          dst_repo_name: syntax-error-safari-starting-template
          username: jpratt-mru
          email: jpratt@mtroyal.ca
